Controllers/ChartCompareController.cs
using Microsoft.AspNetCore.Mvc;
using OxyPlot;
using OxyPlot.Series;
using OxyPlot.WindowsForms;

namespace FinTracer.Controllers
{
    public class ChartCompareController : Controller
    {
        private readonly IConfiguration _configuration;      
        public ChartCompareController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [ResponseCache(Duration = 300)]
        public ActionResult GetFiles()
        {
            string _reportingPath = _configuration["Reporting:DataPath"] ?? string.Empty;
            var files = ExcelManager.GetFilesWithExtension(_reportingPath, "xlsx");
            return Json(files);
        }

        public IActionResult Generate()
        {
            var plotModel = new PlotModel { Title = "Curve Chart" };

            var lineSeries = new LineSeries
            {
                Title = "Sales"
            };
            lineSeries.Points.Add(new DataPoint(1, 30));
            lineSeries.Points.Add(new DataPoint(2, 45));
            lineSeries.Points.Add(new DataPoint(3, 60));
            lineSeries.Points.Add(new DataPoint(4, 50));
            lineSeries.Points.Add(new DataPoint(5, 70));
            lineSeries.Points.Add(new DataPoint(6, 90));
            lineSeries.Points.Add(new DataPoint(7, 100));

            // Add series to plot model
            plotModel.Series.Add(lineSeries);

            // Render and save the chart
            var pngExporter = new PngExporter { Width = 800, Height = 400 };
            pngExporter.ExportToFile(plotModel, "C:\\temp\\curve_chart.png");
            return Json("Done");
        }


        [HttpGet]
        public IActionResult DownloadFile(string filename)
        {

            string _reportingPath = _configuration["Reporting:DataPath"] ?? string.Empty;
            string filePath = $"{_reportingPath}\\{filename}";

            if (string.IsNullOrEmpty(filePath))
            {
                return BadRequest("File path cannot be null or empty.");
            }

            // Ensure the file exists
            if (!System.IO.File.Exists(filePath))
            {
                return NotFound("File not found.");
            }

            try
            {
                // Get file bytes and name
                var fileBytes = System.IO.File.ReadAllBytes(filePath);
                var fileName = Path.GetFileName(filePath);

                // Set the MIME type for Excel and CSV
                string mimeType = fileName.EndsWith(".csv") ? "text/csv" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

                // Return the file for download
                return File(fileBytes, mimeType, fileName);
            }
            catch (Exception ex)
            {
                // Handle any exceptions
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }

        [ResponseCache(Duration = 3600)]
        public ActionResult GetColumns(string excel= "Book_3.xlsx")
        {
            //int _limitRowsFrom = 2;
            //int _limitRowsTo = 100;
            //int.TryParse(_configuration["Limit.Rows.From"], out _limitRowsFrom);
            //int.TryParse(_configuration["Limit.Rows.From"], out _limitRowsTo);
            string _reportingPath = _configuration["Reporting:DataPath"] ?? string.Empty;

            var cols = ExcelManager.ReadFirstRow($"{_reportingPath}\\{excel}");
            return Json(cols);
        }


        public ActionResult GetMaturities(string excel = "Book_3.xlsx")
        {
            string _reportingPath = _configuration["Reporting:DataPath"] ?? string.Empty;
            var maturities = ExcelManager.GetMaturities($"{_reportingPath}\\{excel}");
            return Json(maturities);
        }


        public ActionResult GetSerie(string name, string excel = "Book_3.xlsx")
        {
            string _reportingPath = _configuration["Reporting:DataPath"] ?? string.Empty;

            var serie = ExcelManager.GetColumnsByHeaders($"{_reportingPath}\\{excel}", name);
            return Json(serie);
        }

        public ActionResult GetSeries(string names, string excel = "Book_3.xlsx")
        {
            string _reportingPath = _configuration["Reporting:DataPath"] ?? string.Empty;
            var series = ExcelManager.GetColumnsByHeaders($"{_reportingPath}\\{excel}",names);

            return Json(series);
        }


        public ActionResult GetRandomSeries()
        {
            var result = ExcelManager.GenerateRandomCurves();
            return Json(result);
        }


        public ActionResult GetCategories()
        {
            string _reportingPath = _configuration["Reporting:DataPath"] ?? string.Empty;
            var cols = ExcelManager.ReadFirstRow($"{_reportingPath}\\Book_3.xlsx");
            return Json(cols);
        }


        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Scatter()
        {
            return View();
        }

        public ActionResult Heatmap()
        {
            return View();
        }

        public ActionResult Bands()
        {
            return View();
        }


        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/TimelineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FinTracer.Models;

namespace FinTracer.Controllers
{
    public class TimelineController : Controller
    {
        private readonly FinTraceContext _context;

        public TimelineController(FinTraceContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Timelines.OrderByDescending(t => t.CreatedAt).ToListAsync());
        }

        public async Task<IActionResult> Json()
        {
            return Json(await _context.Timelines.OrderByDescending(t => t.CreatedAt).ToListAsync());
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeline = await _context.Timelines
                .FirstOrDefaultAsync(m => m.TimeLineId == id);
            if (timeline == null)
            {
                return NotFound();
            }

            return View(timeline);
        }

        // GET: Timeline/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TimeLineId,CreatedAt,Username,Title,SubTitle,Category,Source,Series,XAxis,YAxis,Tooltip,Notes,ChartType,Settings,Enabled")] Timeline timeline)
        {
            if (ModelState.IsValid)
            {
                timeline.TimeLineId = Guid.NewGuid();
                _context.Add(timeline);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(timeline);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateJ([Bind("TimeLineId,CreatedAt,Username,Title,SubTitle,Category,Source,Series,XAxis,YAxis,Tooltip,Notes,ChartType,Settings,Enabled")] Timeline timeline)
        {
            if (ModelState.IsValid)
            {
                timeline.TimeLineId = Guid.NewGuid();
                _context.Add(timeline);
                await _context.SaveChangesAsync();
                return Json(timeline);
            }
            return Json(timeline);
        }


        // GET: Timeline/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeline = await _context.Timelines.FindAsync(id);
            if (timeline == null)
            {
                return NotFound();
            }
            return View(timeline);
        }

        // POST: Timeline/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("TimeLineId,CreatedAt,Username,Title,Notes,ChartType,Settings,Enabled")] Timeline timeline)
        {
            if (id != timeline.TimeLineId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timeline);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimelineExists(timeline.TimeLineId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(timeline);
        }

        // GET: Timeline/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeline = await _context.Timelines
                .FirstOrDefaultAsync(m => m.TimeLineId == id);
            if (timeline == null)
            {
                return NotFound();
            }

            return View(timeline);
        }

        // POST: Timeline/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var timeline = await _context.Timelines.FindAsync(id);
            if (timeline != null)
            {
                _context.Timelines.Remove(timeline);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimelineExists(Guid id)
        {
            return _context.Timelines.Any(e => e.TimeLineId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinTracer</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinTracer.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/timeline-7.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    
    <script src="~/js/highcharts/highcharts.js"></script>
    <script src="~/js/highcharts/series-label.js"></script>
    <script src="~/js/highcharts/exporting.js"></script>
    <script src="~/js/highcharts/offline-exporting.js"></script>
    <script src="~/js/highcharts/export-data.js"></script>
    <script src="~/js/highcharts/accessibility.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinTracer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">🏠 Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChartCompare" asp-action="Index">📊 Chart</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Timeline" asp-action="Index">📅 Timeline</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileTransfers" asp-action="Index">📂 Transfers</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Compare">📄 Compare</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">🔒 Privacy</a>
                        </li>
                        <!--li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="File">📇 Files</a>
                        </li-->

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FinTracer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>